version: '3'
services:
    webpack:
        image: node:12
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        command: bash -c "cd /app && yarn install && yarn start"
